### PR TITLE
Add missing lookups to open_multi

### PR DESCRIPTION
**Pull request by andresdelfino**
This adds a few missing lookups and provides a clearer example for each lookup.

New lookups, given original path "`DiR/fiLE.ExT`":

`DIR/FILE.EXT` (original, uppercase)
`dir/file.ext` (original, lowercase)
`ext/dir/file.ext` (original with resource type prefix, lowercase)
`EXT/FILE.EXT` (original filename with resource type prefix, uppercase)

I couldn't determine when the 

#ifdef DEBUG
  if ( f = fpopen(full, mode))
    return f;
#endif

must be used.

This is far from perfect, but at least is consistent with looking for verbatim/uppercase/lowercase in the same places.

### CODE REVIEW

**Comment by MikeDX** [comment]
Sorry I didn't see this earlier. I think we have a problem with div at the moment in that we have two "main" branches on diferent repos that are out of sync, each with different changes / fixes.

**Comment by andresdelfino** [comment]
> Sorry I didn't see this earlier. I think we have a problem with div at the moment in that we have two "main" branches on diferent repos that are out of sync, each with different changes / fixes.

No problem! Where should new PRs go for main div?

**Comment by MikeDX** [comment]
I think DIVGAMES/Div-Games-Studio should be the main div repo and I will merge my changes into that :)

**Comment by andresdelfino** [comment]
Great!

**Pull request closed without merging**
